name: Experiment
on: 
  schedule:
    - cron: '0 */6 * * 6'

  workflow_dispatch:

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: |
        date -u >> generated.txt
        python3 d1.py
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push

    - run: |
        curl -X POST -H 'Content-type: application/json' ${{ secrets.SLACK_WEBHOOKS_URL }} --data '{"text":"股東人數取得完畢"}'
