name: Experiment
on: 
  schedule:
    - cron: '23 4 * * *'
    - cron: '*/6 4 * * *'

  workflow_dispatch:
  

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: List files
      run: ls
    - run: date -u
    
